# Generated by Django 4.2.5 on 2023-10-25 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CrProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VACUUM', (('VAC_CORDLESS_STICK', 'Cordless Stick Vacuum'), ('VAC_CORDLESS_MOP', 'Cordless Mop/Wet Vacuum'), ('VAC_CORDED_UPRIGHT', 'Corded Upright Vacuum'), ('VAC_CORDED_STICK', 'Corded Stick Vacuum'), ('VAC_CORDED_CANISTER', 'Corded Canister Vacuum'), ('VAC_ROBOT', 'Robot Vacuum'), ('VAC_ROBOT_MOP', 'Robot Mop')))], max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('predicted_reliability', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_satisfaction', models.CharField(blank=True, max_length=100, null=True)),
                ('score1', models.FloatField(blank=True, null=True)),
                ('score2', models.FloatField(blank=True, null=True)),
                ('score3', models.FloatField(blank=True, null=True)),
                ('score4', models.FloatField(blank=True, null=True)),
                ('score5', models.FloatField(blank=True, null=True)),
                ('score6', models.FloatField(blank=True, null=True)),
                ('score7', models.FloatField(blank=True, null=True)),
                ('score8', models.FloatField(blank=True, null=True)),
                ('score9', models.FloatField(blank=True, null=True)),
                ('score10', models.FloatField(blank=True, null=True)),
                ('spec1', models.CharField(blank=True, max_length=100, null=True)),
                ('spec2', models.CharField(blank=True, max_length=100, null=True)),
                ('spec3', models.CharField(blank=True, max_length=100, null=True)),
                ('spec4', models.CharField(blank=True, max_length=100, null=True)),
                ('spec5', models.CharField(blank=True, max_length=100, null=True)),
                ('spec6', models.CharField(blank=True, max_length=100, null=True)),
                ('spec7', models.CharField(blank=True, max_length=100, null=True)),
                ('spec8', models.CharField(blank=True, max_length=100, null=True)),
                ('spec9', models.CharField(blank=True, max_length=100, null=True)),
                ('spec10', models.CharField(blank=True, max_length=100, null=True)),
                ('spec11', models.CharField(blank=True, max_length=100, null=True)),
                ('spec12', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VACUUM', (('VAC_CORDLESS_STICK', 'Cordless Stick Vacuum'), ('VAC_CORDLESS_MOP', 'Cordless Mop/Wet Vacuum'), ('VAC_CORDED_UPRIGHT', 'Corded Upright Vacuum'), ('VAC_CORDED_STICK', 'Corded Stick Vacuum'), ('VAC_CORDED_CANISTER', 'Corded Canister Vacuum'), ('VAC_ROBOT', 'Robot Vacuum'), ('VAC_ROBOT_MOP', 'Robot Mop')))], max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vacuum_images')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.IntegerField()),
                ('product_stage', models.CharField(choices=[('MP', 'MP'), ('DV', 'DV')], max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('test_category', models.CharField(choices=[('CR', 'CR'), ('RU', 'Real-Use'), ('FT', 'Field Test'), ('CRDI', 'CRDI')], max_length=100)),
                ('product_category', models.CharField(choices=[('VACUUM', (('VAC_CORDLESS_STICK', 'Cordless Stick Vacuum'), ('VAC_CORDLESS_MOP', 'Cordless Mop/Wet Vacuum'), ('VAC_CORDED_UPRIGHT', 'Corded Upright Vacuum'), ('VAC_CORDED_STICK', 'Corded Stick Vacuum'), ('VAC_CORDED_CANISTER', 'Corded Canister Vacuum'), ('VAC_ROBOT', 'Robot Vacuum'), ('VAC_ROBOT_MOP', 'Robot Mop')))], max_length=100)),
                ('test_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestDetailVacuum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_target', models.CharField(blank=True, max_length=100, null=True)),
                ('test_group', models.CharField(blank=True, max_length=100, null=True)),
                ('test_case', models.CharField(blank=True, max_length=100, null=True)),
                ('brush_type', models.CharField(blank=True, max_length=50, null=True)),
                ('test_measure', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VocReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('reviewer', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('review', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voc_reviews', to='halab.product')),
            ],
        ),
    ]
