# Generated by Django 4.2.5 on 2023-10-25 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetailvacuum',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_detail_vacuums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testdetailvacuum',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halab.sample'),
        ),
        migrations.AddField(
            model_name='testdetailvacuum',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halab.test'),
        ),
        migrations.AddField(
            model_name='testdetailvacuum',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='samples',
            field=models.ManyToManyField(to='halab.sample'),
        ),
        migrations.AddField(
            model_name='test',
            name='testers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacuum_inventories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halab.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halab.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='halab.category'),
        ),
        migrations.AddField(
            model_name='crproductdata',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cr_product_data', to='halab.product'),
        ),
    ]
